export const getHeaderMenu: string = '/menu/getHeaderMenu'
export const getMenuList: string = '/menu/listMenu'
export const saveMenu: string = '/menu/addMenu'
export const updateMenu: string = '/menu/updateMenu'
export const getBlogList: string = '/blog/queryList'
export const getCountyList: string = '/country/getCountryName'
export const getTypeList: string = '/blogType/getBlogType'
export const login: string = '/user/login'
export const fileUploading: string = '/file/upload'
export const fileDownloading: string = '/file/download'
export const addBlog: string = '/blog/addBlog'
export const queryList: string = '/blog/queryList'
export const getBlog: string = '/blog/getBlog'
export const getBlogType: string = '/blogType/getBlogType'
export const modifyBlog: string = '/blog/modifyBlog' //修改文章详细
export const delBlog: string = '/blog/delBlog' //删除文章
export const addClient: string = '/client/add' //删除文章
